### ISSUE TITLE
how to hook windows api? are  there any example of that?

### ISSUE THREAD

**Issue by shawn-li-zh** [Jakobzs/minhook#2]

**Comment by Jakobzs** [comment]
Hey,

You can hook Windows API using the `create_hook_api` function. I do it for example like this for OpenGL hooking.

```rust
    unsafe {
        OPENGL32_WGL_SWAP_BUFFERS.get_or_init(|| {
            mem::transmute(
                MinHook::create_hook_api(
                    "opengl32.dll",
                    "wglSwapBuffers",
                    opengl32_wglswapbuffers as _,
                )
                .unwrap(),
            )
        });
    }
```
, where `OPENGL32_WGL_SWAP_BUFFERS` is a OnceCell of type: `pub static OPENGL32_WGL_SWAP_BUFFERS: OnceCell<FnOpenGl32WglSwapBuffers> = OnceCell::new();`, with the struct being the following: `pub type FnOpenGl32WglSwapBuffers = unsafe extern "system" fn(HDC) -> HRESULT;`

And `opengl32_wglswapbuffers` is a function with the following signature: `pub unsafe extern "system" fn opengl32_wglswapbuffers(hdc: HDC) -> HRESULT { ... }`

I can recommend looking at the [windows](https://github.com/microsoft/windows-rs) crate to see and call most Windows API.

**Comment by shawn-li-zh** [comment]
ok,thank you
